name: contador
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  carousel_slider: ^3.0.0
  audioplayers: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: SourceSansPro
      fonts:
       - asset: assets/SourceSansPro-Regular.ttf
    - family: Creepster
      fonts:
       - asset: assets/Creepster-Regular.ttf